### ISSUE TITLE
Why you get entire bootstrap?

### ISSUE THREAD

**Issue by Brayan-724** [Ioniva/svelte-duallistbox#1]
In `public` folder is another folder called `bootstrap` and it has the entire bootstrap library.
Why you do that?

[Go to folder](https://github.com/Ioniva/svelte-duallistbox/tree/0a19c0a8a4578614fcc429acf70b349f22d7b9ee/public/bootstrap)

**Comment by Brayan-724** [comment]
Why you get the library and upload it to github?
Can't you get it from node_modules or someone else?

**Comment by Ioniva** [comment]
It is because Svelte and Bootstrap do not have (or had) a good integration.
But yes, you're right, I should remove it from package.json.
